name: Snapshot

on:
  schedule:
    - cron: "*/10 * * * *" # Esegui ogni 10 minuti
  workflow_dispatch:       # Possibilità di lanciarlo manualmente

  permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt pandas ta

      - name: Run snapshot script
        run: |
          python main_snapshot.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/snapshot.json docs/changes.json docs/signals_feed.txt docs/changes_feed.txt || true
          if ! git diff --cached --quiet; then
            git commit -m "Update snapshots ($(date -u +"%Y-%m-%dT%H:%M:%SZ"))"
            git push
          else
            echo "No changes to commit."
          fi
